### ISSUE TITLE
Nitro badge.

### ISSUE THREAD

**Issue by kyoyawashere** [AndreMor955/gidget#13]
How did you get the Nitro badge(s) ? I'm wondering about that.

Thanks.

**Comment by AndreMor955** [comment]
The way how I detect if a user has Nitro or not is via their previously authorized accessToken with the scope "identify" to Gidget.

Once that's done I just make a request to Discord with Bearer type token about it.
Unlike a common request with the Bot token, this gives me more information about the user, such as in which language someone uses Discord every day.

And from there I also find out what type of Nitro the user has.

You can go to see the specific code here: https://github.com/AndreMor955/gidget/blob/e779f949ea64fcd43ddda16a8c79e511e78f5cdb/src/structures.js#L361
See my dashboard, this is where I ask them to log in if they want to know such information: https://github.com/AndreMor955/dashboard

Hope I helped :)
