### ISSUE TITLE
Tremenda porquería

### ISSUE THREAD

**Issue by Hyuuh** [AndreMor955/gidget#21]
Nunca he visto tanto código y tanta pena la vez, me siento decepcionado porque eres soporte de MyBOT. Nunca creí que fueras tan otaku de estar editando cada rato tu código y siempre salga mal. Por favor, bórralo y báñate, porque desde acá huelo tu peste. Por cierto, si no me das tu token, te baneo de MyBOT

**Comment by AndreMor955** [comment]
Gracias por su feedback :)

**Comment by Monoverde888** [comment]
![lulwot](https://cdn.discordapp.com/emojis/499775264461422605.png?v=1)
